<?php
/**
 * Translation helpers.
 *
 * UI strings use the English text as the key with {placeholders} — the same
 * keys as the prototype's locale files, so the existing translations are reused
 * as-is (languages/egypt-roamer-{locale}.l10n.php, generated by
 * tools/build-translations.mjs).
 */

defined( 'ABSPATH' ) || exit;

add_action( 'after_setup_theme', static function () {
	load_theme_textdomain( 'egypt-roamer', ER_THEME_DIR . '/languages' );
} );

/** Translate a UI string and fill {placeholders}. Returns unescaped text. */
function er_t( string $text, array $vars = [] ): string {
	$out = translate( $text, 'egypt-roamer' ); // phpcs:ignore WordPress.WP.I18n -- keys are shared with the JS dictionaries
	if ( $vars ) {
		$map = [];
		foreach ( $vars as $k => $v ) {
			$map[ '{' . $k . '}' ] = (string) $v;
		}
		$out = strtr( $out, $map );
	}
	return $out;
}

/** Echo an escaped UI string. */
function er_e( string $text, array $vars = [] ): void {
	echo esc_html( er_t( $text, $vars ) );
}

/** Current language slug (Polylang when active). */
function er_lang(): string {
	return function_exists( 'er_current_lang' ) ? er_current_lang() : substr( determine_locale(), 0, 2 );
}

/** Languages the interface JavaScript has dictionaries for. */
function er_js_languages(): array {
	return [ 'en', 'de', 'fr', 'it', 'es', 'ru', 'zh', 'ar' ];
}
