#!/usr/bin/env python3
"""Egypt Roamer JS bundler (recreates the tool the prototype's README refers to).

Wraps ES modules into one classic script, so the page works over file:// and
without a module loader:

    __m["path.js"] = (() => { ...body...; return { exports }; })();

Usage
  python tools/build.py prototype   # Egypt Roamer/assets/js/main.js -> app.js (the static prototype)
  python tools/build.py theme       # theme src -> assets/js/{home,site}.js + locales/<code>.js
                                    #   + assets/css/bundle-{home,site}.css (see CSS_BUNDLES)
  python tools/build.py check       # rebuild the prototype in memory and compare with its app.js
"""
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROTO = ROOT / "Egypt Roamer" / "assets" / "js"
THEME = ROOT / "wordpress" / "wp-content" / "themes" / "egypt-roamer"
THEME_SRC = THEME / "src" / "js"
THEME_OUT = THEME / "assets" / "js"
THEME_CSS = THEME / "assets" / "css"

# The stylesheets every page needs, in cascade order, served as one file per template instead of six or
# seven render-blocking requests (docs/PERFORMANCE-2026-10-02.md). The sources stay the files to edit; the
# bundles sit next to them, so relative url(../fonts/...) paths resolve the same. Only comments, indentation
# and blank lines are removed: every rule, and its order, is kept. Language-only sheets (fonts-arabic.css,
# rtl.css) stay separate and load after the bundle as before.
CSS_BUNDLES = {
    "bundle-home.css": ["fonts", "tokens", "base", "layout", "journey", "sections", "pages"],
    "bundle-site.css": ["fonts", "tokens", "base", "layout", "sections", "pages"],
}

IMPORT_RE = re.compile(r'^import\s+(.+?)\s+from\s+"(.+?)";\s*$')
EXPORT_DECL_RE = re.compile(r"^export\s+(const|let|function|class|async function)\s+([A-Za-z_$][\w$]*)")
EXPORT_LIST_RE = re.compile(r"^export\s*\{([^}]*)\};\s*$")


def resolve(base: str, spec: str) -> str:
    parts = (pathlib.PurePosixPath(base).parent / spec).parts
    out = []
    for p in parts:
        if p == "..":
            out.pop()
        elif p != ".":
            out.append(p)
    return "/".join(out)


def parse(src_dir: pathlib.Path, path: str, stubs: set):
    """Return (imports, body_lines, exports) for one module."""
    text = (src_dir / path).read_text(encoding="utf-8")
    # Collapse multi-line named imports onto one line: import { a, b } from "x";
    text = re.sub(
        r"import\s*\{([^}]*)\}\s*from\s*\"([^\"]+)\";",
        lambda m: "import { " + ", ".join(n.strip() for n in m.group(1).split(",") if n.strip()) + ' } from "' + m.group(2) + '";',
        text,
    )
    imports, body, exports = [], [], []
    for line in text.split("\n"):
        m = IMPORT_RE.match(line)
        if m:
            what, spec = m.groups()
            dep = resolve(path, spec)
            imports.append(dep)
            if what.startswith("* as "):
                body.append(f'const {what[5:].strip()} = __m["{dep}"];')
            else:
                body.append(f'const {what} = __m["{dep}"];')
            continue
        m = EXPORT_LIST_RE.match(line)
        if m:
            exports += [n.strip() for n in m.group(1).split(",") if n.strip()]
            continue
        m = EXPORT_DECL_RE.match(line)
        if m:
            exports.append(m.group(2))
            line = line[len("export "):]
        body.append(line)
    if path in stubs:  # language dictionaries shipped as separate files in the theme build
        body = [f"const {e} = null;" for e in exports]
    while body and body[-1].strip() == "":
        body.pop()
    return imports, body, exports


def bundle(src_dir: pathlib.Path, entry: str, stubs=frozenset(), banner="") -> str:
    order, seen, mods = [], set(), {}

    def visit(p):
        if p in seen:
            return
        seen.add(p)
        imports, body, exports = parse(src_dir, p, stubs)
        mods[p] = (body, exports)
        for d in imports:
            visit(d)
        order.append(p)

    visit(entry)
    out = [banner.rstrip("\n"), "(function () {", '  "use strict";', "  const __m = {};", ""]
    for p in order:
        body, exports = mods[p]
        out.append(f"  /* ---- {p} ---- */")
        out.append(f'  __m["{p}"] = (() => {{')
        out += [("  " + l) if l.strip() else "" for l in body]
        out.append(f"  return {{ {', '.join(exports)} }};")
        out.append("  })();")
    out.append("})();")
    return "\n".join(out) + "\n"


def module_blocks(bundle_text: str) -> dict:
    blocks, cur, name = {}, [], None
    for line in bundle_text.split("\n"):
        m = re.match(r"^  /\* ---- (.+?) ---- \*/$", line)
        if m:
            if name:
                blocks[name] = cur
            name, cur = m.group(1), []
        elif name and line.strip():
            cur.append(line.rstrip())
    if name:
        blocks[name] = cur
    return blocks


PROTO_BANNER = """/* GENERATED by tools/build.py — do not edit.
   Edit the modules in assets/js/ and re-run: python tools/build.py */
"""


def build_prototype(write=True) -> str:
    text = bundle(PROTO, "main.js", banner=PROTO_BANNER)
    if write:
        (PROTO / "app.js").write_text(text, encoding="utf-8", newline="\n")
    return text


def check():
    ours = module_blocks(build_prototype(write=False))
    theirs = module_blocks((PROTO / "app.js").read_text(encoding="utf-8"))
    ok = True
    for name in sorted(set(ours) | set(theirs)):
        a, b = ours.get(name), theirs.get(name)
        if a != b:
            ok = False
            print("DIFF", name, "(missing)" if a is None or b is None else "")
    print("prototype bundle reproduced module-for-module" if ok else "prototype bundle differs")
    return ok


LOCALES = ["de", "fr", "it", "es", "ru", "zh", "ar"]


def strip_css(text: str) -> str:
    """Drop comments (outside strings), indentation and blank lines; nothing else changes."""
    out, i, n, quote = [], 0, len(text), None
    while i < n:
        c = text[i]
        if quote:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 1
            elif c == quote:
                quote = None
        elif c in "\"'":
            quote = c
            out.append(c)
        elif text.startswith("/*", i):
            end = text.find("*/", i + 2)
            i = n if end < 0 else end + 2
            continue
        else:
            out.append(c)
        i += 1
    return "\n".join(line.strip() for line in "".join(out).splitlines() if line.strip()) + "\n"


def css_bundle(names) -> str:
    parts = ["/* GENERATED by tools/build.py from " + ", ".join(f"{n}.css" for n in names) + " — do not edit. */\n"]
    for name in names:
        parts.append(strip_css((THEME_CSS / f"{name}.css").read_text(encoding="utf-8")))
    return "".join(parts)


def build_theme():
    THEME_OUT.mkdir(parents=True, exist_ok=True)
    stubs = {f"locales/{c}.js" for c in LOCALES}
    banner = "/* GENERATED by tools/build.py from src/js — do not edit. */\n"
    for entry, out in (("main.js", "home.js"), ("site-main.js", "site.js"), ("assistant.js", "assistant.js")):
        text = bundle(THEME_SRC, entry, stubs=stubs, banner=banner)
        (THEME_OUT / out).write_text(text, encoding="utf-8", newline="\n")  # LF on Windows too
        print("wrote", out, len(text.encode()), "bytes")
    for out, names in CSS_BUNDLES.items():
        text = css_bundle(names)
        (THEME_CSS / out).write_text(text, encoding="utf-8", newline="\n")
        print("wrote", out, len(text.encode()), "bytes")
    # One small file per language: window.ER_I18N = { code, meta, html, ui }
    (THEME_OUT / "locales").mkdir(exist_ok=True)
    js = (
        "const code = process.argv[1];"
        "import(require('url').pathToFileURL(process.argv[2]).href).then((m) => {"
        "const d = m[code]; process.stdout.write(JSON.stringify({ code, meta: d.meta, html: d.html, ui: d.ui }));});"
    )
    for code in LOCALES:
        data = subprocess.run(["node", "-e", js, code, str(THEME_SRC / "locales" / f"{code}.js")], capture_output=True, text=True, check=True).stdout
        (THEME_OUT / "locales" / f"{code}.js").write_text(banner + "window.ER_I18N = " + data + ";\n", encoding="utf-8", newline="\n")
    print("wrote locales:", ", ".join(LOCALES))


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    if cmd == "prototype":
        build_prototype()
        print("wrote", PROTO / "app.js")
    elif cmd == "theme":
        build_theme()
    elif cmd == "check":
        sys.exit(0 if check() else 1)
    else:
        print(__doc__)
        sys.exit(2)
